spring.application.name=DuocDesk

# --- Configuración de Oracle Wallet (con URL completa) ---

# 1. URL de Conexión Completa (copiada de tnsnames.ora)
#    ¡OJO! Todo esto debe ir en UNA SOLA LÍNEA en tu archivo .properties
spring.datasource.url=jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g534b68638d1b2a_duocdesk_tp.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))

# 2. Credenciales
spring.datasource.username=admin
spring.datasource.password=vXJzsDyKLB5P8N6

# 3. Driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 4. Ubicación de la Wallet (AÚN ES NECESARIA)
#    La necesitamos para que el protocolo 'tcps' encuentre los certificados
spring.datasource.wallet_location=classpath:Wallet_DuocDesk


# --- Configuración de Logs para Desarrollo ---

# 1. Muestra las solicitudes web (GET, POST) que llegan
#    (Ideal para ver la URL, el código de estado, etc.)
logging.level.org.springframework.web=DEBUG

# 2. Muestra la consulta SQL exacta que Hibernate/JPA envía a Oracle
spring.jpa.show-sql=true

# 3. Formatea esa consulta SQL para que sea más fácil de leer
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl